plugins {
	id 'fabric-loom' version '1.15.3' apply false
	id 'net.fabricmc.fabric-loom-remap' version '1.15.3' apply false
	// https://github.com/Fallen-Breath/preprocessor
	id 'com.replaymod.preprocess' version 'c5abb4fb12'
}

preprocess {
	strictExtraMappings = false

	def mc12110 = createNode('1.21.10', 1_21_10, '')
	def mc261   = createNode('26.1',   26_01_00, '')

	mc12110.link(mc261, file('versions/mapping-1.21.10-26.1.txt'))

	for (final def node in getNodes()) {
		findProject(node.project).ext.mcVersion = node.mcVersion
	}
}

tasks.register('buildAndGather') {
	subprojects {
		dependsOn project.tasks.named('build').get()
	}
	doFirst {
		println 'Gathering builds'
		def buildLibs = { p -> p.layout.buildDirectory.get().asFile.toPath().resolve('libs') }
		delete fileTree(buildLibs(rootProject)) { include '*' }
		subprojects {
			copy {
				from(buildLibs(project)) {
					include '*.jar'
					exclude '*-dev.jar', '*-sources.jar', '*-shadow.jar'
				}
				into buildLibs(rootProject)
				duplicatesStrategy = DuplicatesStrategy.INCLUDE
			}
		}
	}
}

tasks.withType(JavaCompile) {
	options.compilerArgs << '-Xlint:-processing'
}
