# MC 1.21.2 + 1.21.3
minecraft_version=1.21.3
parchment_version=2024.12.07

minecraft_dependency=>=1.21.2 <=1.21.3
carpet_dependency=>=1.4.158

# https://masa.dy.fi/maven/carpet/fabric-carpet/
carpet_core_version=1.21.2-1.4.158+v241022

fabric_api_version=0.114.1+1.21.3

# Resource pack format for this MC version
pack_format=48
