# MC 1.21.10 (obfuscated)
minecraft_version=1.21.10
parchment_version=2025.10.12

minecraft_dependency=>=1.21.9 <=1.21.10
carpet_dependency=>=1.4.184

# https://masa.dy.fi/maven/carpet/fabric-carpet/
carpet_core_version=1.21.10-1.4.188+v251016

fabric_api_version=0.138.4+1.21.10

# Resource pack format for this MC version
pack_format=57
