# MC 1.21.5 (obfuscated)
minecraft_version=1.21.5
parchment_version=2025.06.15

minecraft_dependency=1.21.5
carpet_dependency=>=1.4.169

# https://masa.dy.fi/maven/carpet/fabric-carpet/
carpet_core_version=1.21.5-1.4.169+v250325

fabric_api_version=0.128.2+1.21.5

# Resource pack format for this MC version
pack_format=55
