# MC 1.21.8 (obfuscated, covers 1.21.6 ~ 1.21.8)
minecraft_version=1.21.8
parchment_version=2025.09.14

minecraft_dependency=>=1.21.6 <=1.21.8
carpet_dependency=>=1.4.176

# https://masa.dy.fi/maven/carpet/fabric-carpet/
carpet_core_version=1.21.7-1.4.177+v250630

fabric_api_version=0.133.4+1.21.8

# Resource pack format for this MC version
pack_format=64
